# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0012_auto_20170722_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocoMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wif', models.CharField(max_length=200, null=True)),
                ('user_blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.UserBlockChain')),
            ],
        ),
    ]
