# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 19:28
from __future__ import unicode_literals

import apps.auth_api.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('bitcoin_address', models.CharField(max_length=150, null=True)),
                ('contacts', models.CharField(max_length=250, null=True)),
                ('languages', models.CharField(max_length=250, null=True)),
                ('message', models.CharField(max_length=1024, null=True)),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=100)),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/')),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('posting_key', models.CharField(blank=True, max_length=150, null=True)),
                ('auto_update_position', models.BooleanField(default=True)),
                ('now_not_in_position', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='manager')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', apps.auth_api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_node', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=5)),
                ('blockchain', models.CharField(max_length=15)),
            ],
        ),
    ]
