# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20170601_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.BlockChain')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blockchains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
