# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_auto_20170604_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblockchain',
            unique_together=set([('user', 'blockchain', 'username')]),
        ),
    ]
