# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_auto_20170608_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='btc_wallet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='btc_wallet_direct',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
