# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_auto_20170608_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='address_prefix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='chain_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
