# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_auto_20170612_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='wws',
            new_name='wss',
        ),
    ]
