# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_auto_20170612_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblockchain',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchains', to=settings.AUTH_USER_MODEL),
        ),
    ]
