# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 00:35
from __future__ import unicode_literals

from django.db import migrations


def bc_username_replace(apps, schema_editor):
    UserBlockChain = apps.get_model('auth_api', 'UserBlockChain')
    db_alias = schema_editor.connection.alias

    for user_bc in UserBlockChain.objects.using(db_alias).all():
        user_bc.username = user_bc.username.replace('@', '')
        user_bc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_auto_20170721_2347'),
    ]

    operations = [
        migrations.RunPython(bc_username_replace)
    ]
