# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20170722_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaliRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
