# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0013_emalirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
