# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
