# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passcode', '0002_passrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
