# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('chat_link', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='groups/')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
    ]
