# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
