# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20170601_1659'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser_settings',
            name='blockchain',
        ),
        migrations.RemoveField(
            model_name='page',
            name='locale',
        ),
        migrations.AddField(
            model_name='page',
            name='blockchain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.BlockChain'),
        ),
        migrations.DeleteModel(
            name='Parser_settings',
        ),
    ]
