# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20170601_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='page',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent_permlink',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('author', 'permlink')]),
        ),
    ]
