# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20170607_0351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('author', 'permlink')]),
        ),
    ]
