# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


def change_payout_to_fload(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    db_alias = schema_editor.connection.alias

    for page in Page.objects.using(db_alias).all():
        page.total_payout_value = page.total_payout_value.replace(' GBG', '')
        page.total_pending_payout_value = page.total_pending_payout_value.replace(' GBG', '')
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170607_0441'),
    ]

    operations = [
        migrations.RunPython(change_payout_to_fload),
        migrations.AlterField(
            model_name='page',
            name='total_payout_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='total_pending_payout_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
