# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 20:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_has_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
