# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170809_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='page',
            name='voters',
        ),
    ]
